# Generated by Django 3.0.8 on 2020-11-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_phone_number',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
