# Generated by Django 3.0.8 on 2020-09-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomments',
            options={},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
