# Generated by Django 3.0.8 on 2020-09-30 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200925_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomments',
            old_name='user_name',
            new_name='comment_name',
        ),
        migrations.AlterField(
            model_name='blogcomments',
            name='article_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.BlogPost'),
        ),
    ]
