# Generated by Django 3.0.8 on 2020-10-27 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200930_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomments',
            name='article_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='blog.BlogPost'),
        ),
    ]
