# Generated by Django 3.0.8 on 2020-12-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201027_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomments',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(max_length=254),
        ),
    ]
