# Generated by Django 3.0.8 on 2020-12-13 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20201206_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomments',
            old_name='comment_name',
            new_name='comment_title',
        ),
        migrations.AddField(
            model_name='blogcomments',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
