# Generated by Django 3.0.8 on 2020-09-23 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='county_or_state',
            new_name='county',
        ),
    ]
