# Generated by Django 3.0.8 on 2020-10-27 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200923_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='product_id',
            new_name='product',
        ),
    ]
