# Generated by Django 3.0.8 on 2020-12-26 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_gift_wrapping',
        ),
    ]
