# Generated by Django 3.0.8 on 2021-01-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_remove_order_is_gift_wrapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='product_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
