# Generated by Django 3.0.8 on 2020-08-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200820_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='product_id',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
