# Generated by Django 3.0.8 on 2020-12-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201207_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='URL',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
