# Generated by Django 3.0.8 on 2021-01-06 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20201220_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='name',
            new_name='color_name',
        ),
        migrations.RenameField(
            model_name='flower',
            old_name='name',
            new_name='flower_name',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='image_name',
        ),
    ]
